import os
PREPROCESS_THRESHOLD = 50
PREPROCESS_MINLINELENGTH = 100
PREPROCESS_MAXLINEGAP = 5
PREPROCESS_WIPEWIDTH = 12
PREPROCESS_FIRSTSQUARE = 3
PREPROCESS_SECONDSQUARE = 5
FINDREGION_THRESHOLD = 80
FINDREGION_MINLINELENGTH = 60
FINDREGION_MAXLINEGAP = 15

SLOPE = 1 / 5
MIN_AREA = 1000
MAX_AREA = 10000
MIN_RATIO = 2
MAX_RATIO = 10

SAVE_IMAGES_TAG = True
SAVE_TEXTS_TAG = True
ROOT_PATH = "result/"
if SAVE_IMAGES_TAG:
    IMAGE_PATH = ROOT_PATH + "images/"
    if not os.path.exists(IMAGE_PATH):
        os.makedirs(IMAGE_PATH)
if SAVE_TEXTS_TAG:
    TEXT_PATH = ROOT_PATH + "text/"
    if not os.path.exists(TEXT_PATH):
        os.makedirs(TEXT_PATH)