import os
import readFilePath
import appConfig

PREPROCESS_THRESHOLD = 100
PREPROCESS_MINLINELENGTH = 100
PREPROCESS_MAXLINEGAP = 5
PREPROCESS_WIPEWIDTH = 5
PREPROCESS_FIRSTSQUARE = 3
PREPROCESS_SECONDSQUARE = 5
FINDREGION_THRESHOLD = 40
FINDREGION_MINLINELENGTH = 60
FINDREGION_MAXLINEGAP = 20
SHORT_EXTENSION = -10
LONG_EXTENSION = 470

SLOPE = 1 / 5
MIN_AREA = 1000
MAX_AREA = 10000
MIN_RATIO = 2
MAX_RATIO = 10

SAVE_IMAGES_TAG = appConfig.ds.saveImage
SAVE_TEXTS_TAG = appConfig.ds.saveText
IMAGE_PATH = appConfig.ds.imageSavePath
TEXT_PATH = appConfig.ds.textSavePath