FILELIST_S = "QProgressBar{ "
               " border:none;"
               " background:rgb(230, 230, 230);"
               " border-radius:0px;"
               " text-align:center;"
               " color:gray"
               " }"
            " QProgressBar::chunk{ "
               " background:rgb(71, 137, 250);"
               " border-radius:0px; }"